### ISSUE TITLE
Add a way to create folder in sharepoint

### ISSUE THREAD

**Issue by niconil** [vgrem/Office365-REST-Python-Client#144]
i would like to reopen issue #129

i search to create a folder using API and i have read the answer for #129
i've found this article on this subject
https://www.paitgroup.com/blog/sharepoint-rest-api-and-lists-with-folders
or this :
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest

but it's too low level for me and i prefer to have this enclosed in Office365 python library
Do you think it's possible to have this implemented in Office365-REST-Python-Client ?
and what do you think of the solution ?

**Comment by vgrem** [comment]
Greetings!

The  **create a folder** example from the provided article:


```
url: http://site url/_api/web/folders
method: POST
body: { '__metadata': { 'type': 'SP.Folder' }, 'ServerRelativeUrl': '/document library relative url/folder name'}
Headers: 
    Authorization: "Bearer " + accessToken
    X-RequestDigest: form digest value
    accept: "application/json;odata=verbose"
    content-type: "application/json;odata=verbose"
    content-length:length of post body

```

could be converted to the following example: 

```
target_folder = ctx.web.folders.add("Shared Documents/Archive")
ctx.execute_query()

```
